site_name: Ruia
site_url: https://docs.python-ruia.org/
site_description: An async web scraping micro-framework based on asyncio.
site_author: howie.hu

repo_url: https://github.com/howie6879/ruia
repo_name: 'howie6879/ruia'

copyright: Copyright &copy; 2018 - 2019 <a href="https://github.com/howie6879/ruia">howie.hu</a>.

theme:
  name: 'material'
  logo: './images/logo.png'
  favicon: './images/favicon.ico'

use_directory_urls: false

nav:
  - Introduction: index.md
  - Quick Start: ./en/quickstart.md
  - Tutorials:
      - 1. Overview: ./en/tutorials/overview.md
      - 2. Installation: ./en/tutorials/installation.md
      - 3. Define Data Items: ./en/tutorials/item.md
      - 4. Spider Control: ./en/tutorials/spider.md
      - 5. Request & Response: ./en/tutorials/request.md
      - 6. Customize Middleware: ./en/tutorials/middleware.md
      - 7. Write a Plugins: ./en/tutorials/plugins.md
  - API Guide:
      - Field: ./en/apis/field.md
      - Item: ./en/apis/item.md
      - Spider: ./en/apis/spider.md
      - Request: ./en/apis/request.md
      - Response: ./en/apis/response.md
      - Middleware: ./en/apis/middleware.md
  - Topics:
      - Write Spiders like Scrapy: ./en/topics/write_spiders_like_scrapy.md
      - Item Data Cleaning: ./en/topics/item_data_cleaning.md
  - Examples:
      - Full featured project: ./en/examples/project.md

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: []
  - admonition
  - def_list
  - codehilite